frame_id: world_frame
point_cloud_descriptions:
  - x: 0.2
    y: 0.2
    z: 0.4
    l: 0.1
    w: 0.1
    h: 0.8
    resolution: 0.02
  - x: 0.4
    y: 0.2
    z: 0.4
    l: 0.1
    w: 0.1
    h: 0.8
    resolution: 0.02
